package presentacion;

import entidades.*;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Nícolas Castillo (tecncr@NCR-TOSHIBA)
 */

public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.postulantes = new ArrayList();
        this.carreras = new ArrayList();
        this.postulaciones = new ArrayList();
    }

    
    public static boolean confirmar(String pregunta){
        boolean confirmado = false;
        int resultado = JOptionPane.showConfirmDialog(null, pregunta, "Confirmación", JOptionPane.YES_NO_OPTION);
        if (resultado == JOptionPane.YES_OPTION){
            confirmado = true;
        } else if (resultado == JOptionPane.NO_OPTION){
            confirmado = false;
        }
        return confirmado;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        btnRegPostulante = new javax.swing.JButton();
        btnRegCarrera = new javax.swing.JButton();
        btnRegPostulacion = new javax.swing.JButton();
        btnShowPostulantesCarrera = new javax.swing.JButton();
        btnSearchByCodigo = new javax.swing.JButton();
        btnMostrarTodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema de Registro de Postulantes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Fira Sans", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Universidad Nacional de Trujillo");

        lblSubtitulo.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        lblSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitulo.setText("DIRECCIÓN DE ADMISIÓN");

        btnRegPostulante.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        btnRegPostulante.setText("Registrar Postulante");
        btnRegPostulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegPostulanteActionPerformed(evt);
            }
        });

        btnRegCarrera.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        btnRegCarrera.setText("Registrar Carrera");
        btnRegCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegCarreraActionPerformed(evt);
            }
        });

        btnRegPostulacion.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        btnRegPostulacion.setText("Registrar Postulación");
        btnRegPostulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegPostulacionActionPerformed(evt);
            }
        });

        btnShowPostulantesCarrera.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        btnShowPostulantesCarrera.setText("Mostrar Postulantes por Carrera");
        btnShowPostulantesCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPostulantesCarreraActionPerformed(evt);
            }
        });

        btnSearchByCodigo.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        btnSearchByCodigo.setText("Buscar Postulante por Código");
        btnSearchByCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByCodigoActionPerformed(evt);
            }
        });

        btnMostrarTodo.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        btnMostrarTodo.setText("Mostrar Registro de Postulantes");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSubtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnShowPostulantesCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(52, 52, 52)
                            .addComponent(btnSearchByCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnRegPostulante)
                            .addGap(43, 43, 43)
                            .addComponent(btnRegCarrera)
                            .addGap(33, 33, 33)
                            .addComponent(btnRegPostulacion)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnMostrarTodo)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubtitulo)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegPostulante)
                    .addComponent(btnRegCarrera)
                    .addComponent(btnRegPostulacion))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowPostulantesCarrera)
                    .addComponent(btnSearchByCodigo))
                .addGap(27, 27, 27)
                .addComponent(btnMostrarTodo)
                .addGap(53, 53, 53))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (confirmar("¿Desea salir del programa?"))
            System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void btnRegPostulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegPostulanteActionPerformed
        new FrmRegistrarPostulante(getPostulantes()).setVisible(true);
    }//GEN-LAST:event_btnRegPostulanteActionPerformed

    private void btnRegCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegCarreraActionPerformed
        new FrmRegistrarCarrera(getCarreras()).setVisible(true);
    }//GEN-LAST:event_btnRegCarreraActionPerformed

    private void btnRegPostulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegPostulacionActionPerformed
        new FrmRegPostulacion(getPostulantes(), getCarreras(), getPostulaciones()).setVisible(true);
    }//GEN-LAST:event_btnRegPostulacionActionPerformed

    private void btnShowPostulantesCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPostulantesCarreraActionPerformed
        try{
            Carrera carr = null;
            boolean carrEncont = false;
            boolean postuEncont = false;
            int codcarr = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el código de la carrera que desee buscar", "Búsqueda por carrera", 1));
            for (Carrera c : carreras){
                if (c.getCodigo() == codcarr){
                    carr = c;
                    carrEncont = true;
                }
            }
            if (carrEncont){
                for (Postulacion po : postulaciones){
                    if (po.getPrimeraOpc() == carr){
                        JOptionPane.showMessageDialog(null, po.getP().toString() + po.mostrarMonto(), "Datos del postulante a la carrera", 1);
                        postuEncont = true;
                    }
                }
                if (!postuEncont)
                    JOptionPane.showMessageDialog(null,"No se encontró a ningún postulante en la carrera solicitada", "Postulantes no encontrados", 1);
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró ninguna carrera con el código ingresado", "Carrera no encontrada", 1);
            }
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Por favor ingrese un dato numérico", "Datos ingresados inválidos", 2);
        }
        
    }//GEN-LAST:event_btnShowPostulantesCarreraActionPerformed

    private void btnSearchByCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByCodigoActionPerformed
        try{
            Postulacion post = null;
            boolean postEncont = false;
            int codpost = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el código de postulación\ndel postulante que desee buscar", "Búsqueda por código de postulación", 1));
            for (Postulacion po : postulaciones){
                if (po.getCodigo() == codpost){
                    post = po;
                    postEncont = true;
                }
            }
            if (postEncont)
                JOptionPane.showMessageDialog(null,post.getP().toString(), "Postulante encontrado", 1);
            else
                JOptionPane.showMessageDialog(null, "No se encontró ningún postulante con el código ingresado", "Postulante no encontrado", 1);
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Por favor ingrese un dato numérico", "Datos ingresados inválidos", 2);
        }
    }//GEN-LAST:event_btnSearchByCodigoActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        if (!postulantes.isEmpty()){
            for (Postulante p : postulantes){
                JOptionPane.showMessageDialog(null, p.toString(), "Vista general de todos los postulantes", 1);
            }
        } else {
            JOptionPane.showMessageDialog(null, "El registro de postulantes está vacío", "No hay postulantes", 2);
        }
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf Light look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.out.println(ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JButton btnRegCarrera;
    private javax.swing.JButton btnRegPostulacion;
    private javax.swing.JButton btnRegPostulante;
    private javax.swing.JButton btnSearchByCodigo;
    private javax.swing.JButton btnShowPostulantesCarrera;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Postulacion> postulaciones;
    private ArrayList<Postulante> postulantes;
    private ArrayList<Carrera> carreras;

    public ArrayList<Postulacion> getPostulaciones() {
        return postulaciones;
    }

    public void setPostulaciones(ArrayList<Postulacion> postulaciones) {
        this.postulaciones = postulaciones;
    }

    public ArrayList<Postulante> getPostulantes() {
        return postulantes;
    }

    public void setPostulantes(ArrayList<Postulante> postulantes) {
        this.postulantes = postulantes;
    }

    public ArrayList<Carrera> getCarreras() {
        return carreras;
    }

    public void setCarreras(ArrayList<Carrera> carreras) {
        this.carreras = carreras;
    }
}
