package presentacion;

import entidades.*;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.HeadlessException;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Nícolas Castillo (tecncr@NCR-TOSHIBA)
 */
public class FrmRegPostulacion extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegPostulacion
     */
    public FrmRegPostulacion() {
        initComponents();
    }
    public FrmRegPostulacion(ArrayList<Postulante> postulantes, ArrayList<Carrera> carreras, ArrayList<Postulacion> postulaciones) {
        initComponents();
        this.carreras = carreras;
        this.postulantes = postulantes;
        this.postulaciones = postulaciones;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblCodigo1 = new javax.swing.JLabel();
        lblCodigo2 = new javax.swing.JLabel();
        lblCodigo3 = new javax.swing.JLabel();
        lblCodigo4 = new javax.swing.JLabel();
        txtCodigoPost = new javax.swing.JTextField();
        txtDniPos = new javax.swing.JTextField();
        txtCodCarr1 = new javax.swing.JTextField();
        txtCodCarr2 = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Postulación");

        lblTitulo.setFont(new java.awt.Font("Fira Sans", 1, 24)); // NOI18N
        lblTitulo.setText("Registro de Postulación");

        lblCodigo.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        lblCodigo.setText("Código de Postulación:");

        lblCodigo1.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        lblCodigo1.setText("DNI del Postulante:");

        lblCodigo2.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        lblCodigo2.setText("Código de Carrera (Primera Opción):");

        lblCodigo3.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        lblCodigo3.setText("Código de Carrera (Segunda Opción):");

        lblCodigo4.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        lblCodigo4.setText("Fecha de Postulación:");

        txtCodigoPost.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N

        txtDniPos.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N

        txtCodCarr1.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N

        txtCodCarr2.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N

        txtAnio.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        txtAnio.setText("AAAA");

        txtMes.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        txtMes.setText("MM");

        txtDia.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        txtDia.setText("DD");

        btnRegistrar.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Fira Sans", 0, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo)
                            .addComponent(lblCodigo1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDniPos)
                            .addComponent(txtCodigoPost)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCodigo4)
                        .addGap(18, 18, 18)
                        .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo2)
                            .addComponent(lblCodigo3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodCarr2, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(txtCodCarr1))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitulo)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigoPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo1)
                    .addComponent(txtDniPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo2)
                    .addComponent(txtCodCarr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo3)
                    .addComponent(txtCodCarr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo4)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Postulante postul = null;
        Carrera carr1 = null; Carrera carr2 = null;
        try {
            int codpos = Integer.parseInt(txtCodigoPost.getText());
            String dnipos = txtDniPos.getText();            
            int codigo1 = Integer.parseInt(txtCodCarr1.getText());
            int codigo2 = Integer.parseInt(txtCodCarr2.getText());
            for (Postulante p : postulantes){
                if (p.getDni().equals(dnipos)){
                    postul = p;
                }
            }
            for (Carrera c : carreras){
                if (c.getCodigo() == codigo1){
                    carr1 = c;
                }
            }
            for (Carrera c : carreras){
                if (c.getCodigo() == codigo2){
                    carr2 = c;
                }
            }
            LocalDate fecha = LocalDate.of(Integer.parseInt(txtAnio.getText()),
                                           Integer.parseInt(txtMes.getText()),
                                           Integer.parseInt(txtDia.getText()));
            Postulacion post = new Postulacion(codpos, postul, carr1, carr2, fecha);
            postulaciones.add(post);
            JOptionPane.showMessageDialog(null, "Se registró la postulación correctamente", "Operación exitosa", 1);            
        } catch (HeadlessException | NumberFormatException | DateTimeException ex){
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Rellene todos los campos y verifique la validez de los datos ingresados", "Datos vacíos o inválidos", 2);            
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf Light look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.out.println(ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try{
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new FrmRegPostulacion().setVisible(true);
                }
            });
        } catch (DateTimeException ex){
            JOptionPane.showMessageDialog(null,"Verifique la validez de los valores de fecha","Fecha inválida",2);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigo1;
    private javax.swing.JLabel lblCodigo2;
    private javax.swing.JLabel lblCodigo3;
    private javax.swing.JLabel lblCodigo4;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtCodCarr1;
    private javax.swing.JTextField txtCodCarr2;
    private javax.swing.JTextField txtCodigoPost;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtDniPos;
    private javax.swing.JTextField txtMes;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Carrera> carreras;
    private ArrayList<Postulante> postulantes;
    private ArrayList<Postulacion> postulaciones;
}
